Add storage settings for auto-store/recover of primary sample (#39)
* Add control panel for SENAITE STORAGE

* Better wording (restore -> recover)

* Auto-store/recover primary depending on configuration settings

* Do not store primary if it has it's own analyses assigned

* Added missing whitespace character

* Changelog

* Fix dependency profile error when running tests

```
Traceback (most recent call last):
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/zope.testrunner-5.6-py2.7.egg/zope/testrunner/runner.py", line 475, in run_layer
    setup_layer(options, layer, setup_layers)
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/zope.testrunner-5.6-py2.7.egg/zope/testrunner/runner.py", line 845, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/zope.testrunner-5.6-py2.7.egg/zope/testrunner/runner.py", line 850, in setup_layer
    layer.setUp()
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/plone.app.testing-6.1.9-py2.7.egg/plone/app/testing/helpers.py", line 370, in setUp
    self.setUpPloneSite(portal)
  File "/home/jordi/Desenvolupament/plone5/zinstance/src/senaite.storage/src/senaite/storage/tests/base.py", line 66, in setUpPloneSite
    applyProfile(portal, "senaite.storage:default")
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/plone.app.testing-6.1.9-py2.7.egg/plone/app/testing/helpers.py", line 129, in applyProfile
    blacklisted_steps=blacklisted_steps)
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/Products.GenericSetup-2.3.0-py2.7.egg/Products/GenericSetup/tool.py", line 405, in runAllImportStepsFromProfile
    dependency_strategy=dependency_strategy)
   - __traceback_info__: profile-senaite.storage:default
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/Products.GenericSetup-2.3.0-py2.7.egg/Products/GenericSetup/tool.py", line 1436, in _runImportStepsFromContext
    chain = self.getProfileDependencyChain(profile_id)
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/Products.GenericSetup-2.3.0-py2.7.egg/Products/GenericSetup/tool.py", line 1378, in getProfileDependencyChain
    dependencies = self.getDependenciesForProfile(profile_id)
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/Products.GenericSetup-2.3.0-py2.7.egg/Products/GenericSetup/tool.py", line 974, in getDependenciesForProfile
    % (profile_id, dependency_id))
KeyError: u'Profile "profile-senaite.storage:default" requires the dependency-profile "profile-senaite.lims:default", which does not exist.'
```

* Doctest basics

* Compliment doctest